# Generated by Django 4.0.1 on 2022-01-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='respondent',
            options={'ordering': ['id']},
        ),
    ]
